name: Upload OpenAPI spec to Stainless

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  stainless:
    concurrency: upload-openapi-spec-action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: stainless-api/upload-openapi-spec-action@main
        with:
          stainless_api_key: ${{ secrets.STAINLESS_API_KEY }}
          input_path: 'api-spec/openapi.json'
          config_path: 'api-spec/my.stainless.yaml'
          project_name: 'my-stainless-project'
          # the project name MUST be already created in the Stainless UI
          # and the project name CAN NOT contain language name, like 'go' or 'js'
